const initialState = {
  items: [
    {
      id: 1,
      nameAm: 'ator1',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 2,
      nameAm: 'ator2',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 3,
      nameAm: 'ator3',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 4,
      nameAm: 'ator4',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 5,
      nameAm: 'ator5',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 6,
      nameAm: 'ator6',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 7,
      nameAm: 'ator7',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 8,
      nameAm: 'ator8',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 9,
      nameAm: 'ator9',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
    {
      id: 10,
      nameAm: 'ator10',
      nameRu: 'stul',
      numberCode: '#22546',
      descriptionAm: 'ator e nstelu hamar',
      descriptionRu: 'ruseren ator e nstelu hamar',
      price: '250',
      categorie: 'papuk',
    },
  ],
}

export const ItemReducer = (state = initialState, action) => {
  switch (action.type) {
    default:
      return state
  }
}
